# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_pack <- function(root_obj) {
    .Call('_RcppMsgPack_c_pack', PACKAGE = 'RcppMsgPack', root_obj)
}

c_unpack <- function(char_message) {
    .Call('_RcppMsgPack_c_unpack', PACKAGE = 'RcppMsgPack', char_message)
}

#' Simple MsgPack Example
#' 
#' @details The function provides a simple illustration of MessagePack.
#' @return A boolean value of \code{TRUE} is returned, but the function exists
#' for its side effect.
#' @seealso The MessagePack documentation, particularly the msgpack-c examples.
arrayEx <- function() {
    .Call('_RcppMsgPack_arrayEx', PACKAGE = 'RcppMsgPack')
}

#' Second simple MsgPack Example
#' 
#' @details The function provides a simple illustration of MessagePack.
#' @return A boolean value of \code{TRUE} is returned, but the function exists
#' for its side effect.
#' @seealso The MessagePack documentation, particularly the msgpack-c examples.
enumEx <- function() {
    .Call('_RcppMsgPack_enumEx', PACKAGE = 'RcppMsgPack')
}

